apiVersion: v1
kind: ReplicationController
metadata:
  name: user
spec:
  replicas: 1
  selector:
    role: backend
    app: user
    version: 0.0.1
  template:
    metadata:
      labels:
        role: backend
        app: user
        version: 0.0.1
    spec:
      containers:
        - name: user
          image: hharnisc/user
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
