apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    name: user
spec:
  type: LoadBalancer # this assumes you're exposing this service to the outside world
  ports:
    - name: user
      port: 80 # this assumes you're exposing this service to the outside world
      targetPort: 8080
      protocol: TCP
  selector:
    role: backend
    app: user
